source "/usr/local/scripts/tester/testprocs/runsimple.exp"
set testdir "/usr/local/scripts/tester/testsuite/slurm.tests"
# proc runsimple { test_name command_line passtext }
# set verbose 1
# Check that simple batch job is submitted ok
runsimple "01 Basic Submit" "sbatch $testdir/slurm/01_slurm-serial-job-script"  "Submitted batch job"
runsimple "02 Case Sensitive Project Name" "sbatch --account=pMOSP $testdir/slurm/01_slurm-serial-job-script"  "Submitted batch job"
